name: CI  # Nome del workflow

on:
  push:
    branches: [ "main", "master" ] # Esegui su push a questi branch
  pull_request:
    branches: [ "main", "master" ] # Esegui su pull request verso questi branch

jobs:
  build:
    runs-on: ubuntu-latest  # Esegui su Ubuntu

    steps:
      - uses: actions/checkout@v4  # Scarica il codice
      - name: Set up JDK 11  # Configura Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven local repository  # Cache delle dipendenze Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven  # Esegui la build
        run: mvn clean install -B -e